export const questions = [
  "I usually don't laugh or joke around much with other people.",
  "If I am feeling depressed, I can usually cheer myself up with humor.",
  "If someone makes a mistake, I will often tease them about it.",
  "I let people laugh at me or make fun at my expense more than I should.",
  "I don't have to work very hard at making other people laugh — I seem to be a naturally humorous person.",
  "Even when I'm by myself, I'm often amused by the absurdities of life.",
  "People are never offended or hurt by my sense of humor.",
  "I will often get carried away in putting myself down if it makes my family or friends laugh.",
  "I rarely make other people laugh by telling funny stories about myself.",
  "If I am feeling upset or unhappy I usually try to think of something funny about the situation to make myself feel better.",
  "When telling jokes or saying funny things, I am usually not very concerned about how other people are taking it.",
  "I often try to make people like or accept me more by saying something funny about my own weaknesses, blunders, or faults.",
  "I laugh and joke a lot with my friends.",
  "My humorous outlook on life keeps me from getting overly upset or depressed about things.",
  "I do not like it when people use humor as a way of criticizing or putting someone down.",
  "I don't often say funny things to put myself down.",
  "I usually don't like to tell jokes or amuse people.",
  "If I'm by myself and I'm feeling unhappy, I make an effort to think of something funny to cheer myself up.",
  "Sometimes I think of something that is so funny that I can't stop myself from saying it, even if it is not appropriate for the situation.",
  "I often go overboard in putting myself down when I am making jokes or trying to be funny.",
  "I enjoy making people laugh.",
  "If I am feeling sad or upset, I usually lose my sense of humor.",
  "I never participate in laughing at others even if all my friends are doing it.",
  "When I am with friends or family, I often seem to be the one that other people make fun of or joke about.",
  "I don't often joke around with my friends.",
  "It is my experience that thinking about some amusing aspect of a situation is often a very effective way of coping with problems.",
  "If I don't like someone, I often use humor or teasing to put them down.",
  "If I am having problems or feeling unhappy, I often cover it up by joking around, so that even my closest friends don't know how I really feel.",
  "I usually can't think of witty things to say when I'm with other people.",
  "I don't need to be with other people to feel amused — I can usually find things to laugh about even when I'm by myself.",
  "Even if something is really funny to me, I will not laugh or joke about it if someone will be offended.",
  "Letting others laugh at me is my way of keeping my friends and family in good spirits."
]